### ISSUE TITLE
As a user I want to see a feed of tweets

### ISSUE THREAD

**Issue by christopher-francisco** [juank1809/twiteer#4]
### Description

When users visits the app, they're greeted with a list of tweets they can read and scroll through.

### AC

* The user sees a list of tweets
* Tweets have user, a message, a favorite count, a reply count, and a retweet count
* Users have a full name, a username
* No user image for the time being. Instead we'll use their initials, i.e: Christopher Francisco would be CF.

### Technical aspects

* Use a hardcoded list of tweets, no fetching yet
* Design is up to the developer

**Comment by juank1809** [comment]
Should I start this feature along with the design system? Or just make a "prototype design" and leave the design system for later?

**Comment by christopher-francisco** [comment]
Design system for later. Prototype design for the time being
